### ISSUE TITLE
能不能直接clone到interface文件夹？

### ISSUE THREAD

**Issue by Charlie441324219** [aby-ui/repo-base#12]
我用clone是clone到repo-base文件夹，然后再粘贴复制到interface文件夹，请问能不能直接clone到interface文件夹，这样更新更方便一些，谢谢。

**Comment by wzyinghid** [comment]
试试把repo-base文件夹的名字改成interface

**Comment by Charlie441324219** [comment]
我GitHub小白，你们是怎么更新的？fetch到repo-base然后复制粘贴到interface？
